:bug: Fix messing up OctoPrint config :art: Add 'server.allowFraming true' to OctoPrint config :art: Hide TouchUI after receiving done signal :art: Remove parse_yaml and always ask for autoLoginAs
Fixes BillyBlaze/OctoPrint-TouchUI#368
Fixes BillyBlaze/OctoPrint-TouchUI#370

diff --git a/helpers/install-steps/6-setup-autologin-as b/helpers/install-steps/6-setup-autologin-as
--- a/helpers/install-steps/6-setup-autologin-as
+++ b/helpers/install-steps/6-setup-autologin-as
@@ -1,11 +1,18 @@
 #!/bin/bash
 source $DIR/functions/successfull
-source $DIR/functions/parse_yaml
 
-eval $(parse_yaml $OCTOPRINT_CONFIG "octoprint_")
+OCTOPRINT_EXEC=$(ps -ef | grep octoprint | grep -v grep | awk '{print $9}')
+OCTOPRINT_EXEC_USER=$(ps -ef | grep octoprint | grep -v grep | awk '{print $1}')
+
 echo ""
-if [ -z "$octoprint_accessControl_autologinAs" ]
+if [ -z $OCTOPRINT_EXEC ]
 then
+	echo "Skipping setup autoLogin for localhost:"
+	echo " - OctoPrint exec path not found. Please create a ticket in GitHub!"
+else
+	# Force allowFraming to be true
+	runCmd su - $OCTOPRINT_EXEC_USER -c "$OCTOPRINT_EXEC config set --bool server.allowFraming true"
+
 	OCTOPRINT_USER=$(whiptail --inputbox \
 		"Insert the username that can auto login into OctoPrint (Leave this empty to skip this step)" \
 		8 78 --title "Setup autoLogin for localhost" 3>&1 1>&2 2>&3)
@@ -13,20 +20,14 @@ then
 	if [ -n "$OCTOPRINT_USER" ]
 	then
 		echo "Saving autoLogin to config ($OCTOPRINT_CONFIG)"
-		NEW="accessControl:\n  autologinLocal: true\n  autologinAs: $OCTOPRINT_USER"
 
-		if [ -n "$(cat $OCTOPRINT_CONFIG | grep accessControl)" ]
-		then
-			runCmd sed -i -e "s/accessControl:/$NEW/g" $OCTOPRINT_CONFIG
-			successfull $?
-		else
-			echo "$NEW" >> $OCTOPRINT_CONFIG
-			successfull $?
-		fi
+		runCmd runCmd su - $OCTOPRINT_EXEC_USER -c "$OCTOPRINT_EXEC config set --bool accessControl.autologinLocal true"
+		runCmd runCmd su - $OCTOPRINT_EXEC_USER -c "$OCTOPRINT_EXEC config set accessControl.autologinAs $OCTOPRINT_USER"
 
-		sleep 1
+		CAN_REBOOT=$(whiptail \
+			--yesno "Can we restart OctoPrint? (If not; you need to restart OctoPrint manually before you can make use of the autoLogin configuration)" 8 78 3>&1 1>&2 2>&3)
 
-		if (whiptail --yesno "Can we restart OctoPrint? (If not; you need to restart OctoPrint manually before you can make use of the autoLogin configuration)" 8 78)
+		if [ -n "$CAN_REBOOT" ]
 		then
 			echo ""
 			echo "Restarting OctoPrint:"
@@ -37,7 +38,4 @@ then
 		echo "Skipping setup autoLogin for localhost:"
 		echo " - Cancelled by user"
 	fi
-else
-	echo "Skipping setup autoLogin for localhost:"
-	echo " - Login as '$octoprint_accessControl_autologinAs' already configured"
 fi
